### ISSUE TITLE
Imports of modules do not account for directory structure

### ISSUE THREAD

**Issue by mgraber** [katysill/flood-detection#2]
@katysill 

When importing calc_array_mask and morph_indices in ndwi_msi_with_modules, cell two expects these modules to be in the same directory as the notebook. Because they are instead in a separate modules directory, the modules cannot be imported by executing the cell. I would recommend placing modules in the same directory, or use `sys` to make sure your imports are referring to the modules directory.

A potentially helpful explanation: https://stackoverflow.com/questions/4383571/importing-files-from-different-folder

**Comment by katysill** [comment]
Thanks @mgraber. I have updated ndwi_msi_with_modules.ipynb to import and use sys to refer to the modules directory.
