### ISSUE TITLE
Working directory path is hard-coded in ndwi_msi_with_modules, SVM_exploration, and k-means_exploration

### ISSUE THREAD

**Issue by mgraber** [katysill/flood-detection#3]
@katysill 

In the notebooks, working directory paths are hard-coded to be the specific path of your machine. This means that the workflow does not run as-is on another computer. I would recommend instead using relative paths. 

For example, if your notebook is written so that it always assumes imagery are in a directory named "input_images," and you tell your user that this directory needs to be on the same level as the "notebooks" directory, they can run the notebooks regardless of where they download them.

Better yet, create this input_images directory for them, and perhaps place a very low resolution or synthetic sample image in it. Then, whenever the repo is cloned, you know the user will have an example of the correct directory structure.

**Comment by katysill** [comment]
Thanks @mgraber .. Great suggestions.. I am still working on this!
