### ISSUE TITLE
README does not provide data type description or explanation of directory structure

### ISSUE THREAD

**Issue by mgraber** [katysill/flood-detection#4]
@katysill 

In the README, it would be really helpful if you provide an explanation of all of the inputs/outputs of your notebooks. This could include the following for each script:

- The data type of the inputs
- The data types and descriptions of parameter inputs (those things you are asking the user to modify)
- Where, based on pathways relative to the notebooks, these data should live
- Where to acquire these input data
- The data type of the outputs
- Where, again based on relative pathways, these outputs will end up

**Comment by katysill** [comment]
Thanks @mgraber. I have updated the README with your helpful suggestions. This is a bit of a work in progress, and will continue to be updated as the project progresses. For now, I will go ahead and close this issue.
