### ISSUE TITLE
In morph_indices.py, the function selemline is defined within the function calc_msi

### ISSUE THREAD

**Issue by mgraber** [katysill/flood-detection#5]
@katysill 

I think this is just an issue of indentation. The way it is written, the function selemline is redefined every time the function calc_msi is run. It would make more sense to not define one within the other (make selemline its own function). You can still call selemline from calc_msi. But there isn't reason to define it multiple times. 

Separating it also means a user can use selemline without having to do so within calc_msi.

**Comment by katysill** [comment]
Thanks @mgraber. I updated morph_indices.py, defining selemline as a separate function. Great suggestion!
